repos:
  - repo: local
    hooks:
      - id: ruff-fix
        name: ruff fix
        entry: uv --project backend run ruff check --fix
        language: system
        types_or: [python]
        stages: [pre-commit]

      - id: black-format
        name: black format
        entry: uv --project backend run black
        language: system
        types_or: [python]
        stages: [pre-commit]

      - id: quality-pre-push
        name: quality pre-push
        entry: make check
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]
