/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LookupRouteImport } from './routes/lookup'
import { Route as SkillRouteImport } from './routes/skill'
import { Route as AuthenticatedOperationsRouteImport } from './routes/_authenticated/operations'
import { Route as AuthenticatedOperationsIndexRouteImport } from './routes/_authenticated/operations.index'
import { Route as AuthenticatedOperationsCorrectionsRouteImport } from './routes/_authenticated/operations.corrections'
import { Route as AuthenticatedOperationsDeliveriesRouteImport } from './routes/_authenticated/operations.deliveries'
import { Route as AuthenticatedOperationsQualityRouteImport } from './routes/_authenticated/operations.quality'
import { Route as AuthenticatedOperationsRawPayloadsRouteImport } from './routes/_authenticated/operations.raw-payloads'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LookupRoute = LookupRouteImport.update({
  id: '/lookup',
  path: '/lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillRoute = SkillRouteImport.update({
  id: '/skill',
  path: '/skill',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOperationsRoute = AuthenticatedOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOperationsIndexRoute =
  AuthenticatedOperationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOperationsRoute,
  } as any)
const AuthenticatedOperationsCorrectionsRoute =
  AuthenticatedOperationsCorrectionsRouteImport.update({
    id: '/corrections',
    path: '/corrections',
    getParentRoute: () => AuthenticatedOperationsRoute,
  } as any)
const AuthenticatedOperationsDeliveriesRoute =
  AuthenticatedOperationsDeliveriesRouteImport.update({
    id: '/deliveries',
    path: '/deliveries',
    getParentRoute: () => AuthenticatedOperationsRoute,
  } as any)
const AuthenticatedOperationsQualityRoute =
  AuthenticatedOperationsQualityRouteImport.update({
    id: '/quality',
    path: '/quality',
    getParentRoute: () => AuthenticatedOperationsRoute,
  } as any)
const AuthenticatedOperationsRawPayloadsRoute =
  AuthenticatedOperationsRawPayloadsRouteImport.update({
    id: '/raw-payloads',
    path: '/raw-payloads',
    getParentRoute: () => AuthenticatedOperationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/lookup': typeof LookupRoute
  '/skill': typeof SkillRoute
  '/operations': typeof AuthenticatedOperationsRouteWithChildren
  '/operations/corrections': typeof AuthenticatedOperationsCorrectionsRoute
  '/operations/deliveries': typeof AuthenticatedOperationsDeliveriesRoute
  '/operations/quality': typeof AuthenticatedOperationsQualityRoute
  '/operations/raw-payloads': typeof AuthenticatedOperationsRawPayloadsRoute
  '/operations/': typeof AuthenticatedOperationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/lookup': typeof LookupRoute
  '/skill': typeof SkillRoute
  '/operations/corrections': typeof AuthenticatedOperationsCorrectionsRoute
  '/operations/deliveries': typeof AuthenticatedOperationsDeliveriesRoute
  '/operations/quality': typeof AuthenticatedOperationsQualityRoute
  '/operations/raw-payloads': typeof AuthenticatedOperationsRawPayloadsRoute
  '/operations': typeof AuthenticatedOperationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/lookup': typeof LookupRoute
  '/skill': typeof SkillRoute
  '/_authenticated/operations': typeof AuthenticatedOperationsRouteWithChildren
  '/_authenticated/operations/corrections': typeof AuthenticatedOperationsCorrectionsRoute
  '/_authenticated/operations/deliveries': typeof AuthenticatedOperationsDeliveriesRoute
  '/_authenticated/operations/quality': typeof AuthenticatedOperationsQualityRoute
  '/_authenticated/operations/raw-payloads': typeof AuthenticatedOperationsRawPayloadsRoute
  '/_authenticated/operations/': typeof AuthenticatedOperationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/lookup'
    | '/skill'
    | '/operations'
    | '/operations/corrections'
    | '/operations/deliveries'
    | '/operations/quality'
    | '/operations/raw-payloads'
    | '/operations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/lookup'
    | '/skill'
    | '/operations/corrections'
    | '/operations/deliveries'
    | '/operations/quality'
    | '/operations/raw-payloads'
    | '/operations'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/lookup'
    | '/skill'
    | '/_authenticated/operations'
    | '/_authenticated/operations/corrections'
    | '/_authenticated/operations/deliveries'
    | '/_authenticated/operations/quality'
    | '/_authenticated/operations/raw-payloads'
    | '/_authenticated/operations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  LookupRoute: typeof LookupRoute
  SkillRoute: typeof SkillRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookup': {
      id: '/lookup'
      path: '/lookup'
      fullPath: '/lookup'
      preLoaderRoute: typeof LookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill': {
      id: '/skill'
      path: '/skill'
      fullPath: '/skill'
      preLoaderRoute: typeof SkillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/operations': {
      id: '/_authenticated/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof AuthenticatedOperationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/operations/': {
      id: '/_authenticated/operations/'
      path: '/'
      fullPath: '/operations/'
      preLoaderRoute: typeof AuthenticatedOperationsIndexRouteImport
      parentRoute: typeof AuthenticatedOperationsRoute
    }
    '/_authenticated/operations/corrections': {
      id: '/_authenticated/operations/corrections'
      path: '/corrections'
      fullPath: '/operations/corrections'
      preLoaderRoute: typeof AuthenticatedOperationsCorrectionsRouteImport
      parentRoute: typeof AuthenticatedOperationsRoute
    }
    '/_authenticated/operations/deliveries': {
      id: '/_authenticated/operations/deliveries'
      path: '/deliveries'
      fullPath: '/operations/deliveries'
      preLoaderRoute: typeof AuthenticatedOperationsDeliveriesRouteImport
      parentRoute: typeof AuthenticatedOperationsRoute
    }
    '/_authenticated/operations/quality': {
      id: '/_authenticated/operations/quality'
      path: '/quality'
      fullPath: '/operations/quality'
      preLoaderRoute: typeof AuthenticatedOperationsQualityRouteImport
      parentRoute: typeof AuthenticatedOperationsRoute
    }
    '/_authenticated/operations/raw-payloads': {
      id: '/_authenticated/operations/raw-payloads'
      path: '/raw-payloads'
      fullPath: '/operations/raw-payloads'
      preLoaderRoute: typeof AuthenticatedOperationsRawPayloadsRouteImport
      parentRoute: typeof AuthenticatedOperationsRoute
    }
  }
}

interface AuthenticatedOperationsRouteChildren {
  AuthenticatedOperationsCorrectionsRoute: typeof AuthenticatedOperationsCorrectionsRoute
  AuthenticatedOperationsDeliveriesRoute: typeof AuthenticatedOperationsDeliveriesRoute
  AuthenticatedOperationsQualityRoute: typeof AuthenticatedOperationsQualityRoute
  AuthenticatedOperationsRawPayloadsRoute: typeof AuthenticatedOperationsRawPayloadsRoute
  AuthenticatedOperationsIndexRoute: typeof AuthenticatedOperationsIndexRoute
}

const AuthenticatedOperationsRouteChildren: AuthenticatedOperationsRouteChildren =
  {
    AuthenticatedOperationsCorrectionsRoute:
      AuthenticatedOperationsCorrectionsRoute,
    AuthenticatedOperationsDeliveriesRoute:
      AuthenticatedOperationsDeliveriesRoute,
    AuthenticatedOperationsQualityRoute: AuthenticatedOperationsQualityRoute,
    AuthenticatedOperationsRawPayloadsRoute:
      AuthenticatedOperationsRawPayloadsRoute,
    AuthenticatedOperationsIndexRoute: AuthenticatedOperationsIndexRoute,
  }

const AuthenticatedOperationsRouteWithChildren =
  AuthenticatedOperationsRoute._addFileChildren(
    AuthenticatedOperationsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedOperationsRoute: typeof AuthenticatedOperationsRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedOperationsRoute: AuthenticatedOperationsRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  LookupRoute: LookupRoute,
  SkillRoute: SkillRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
