-- psql load script generated by scripts/partial_dump.py
-- Run: psql "$DATABASE_URL" -f load.sql
-- NOTE: on_conflict=upsert. This script uses direct \copy and does not implement merge semantics.
BEGIN;

-- disable trigger/FK checks during load (local development use only)
SET session_replication_role = replica;

TRUNCATE TABLE "public"."dataset_registry" CASCADE;
TRUNCATE TABLE "public"."ingestion_run" CASCADE;
TRUNCATE TABLE "public"."instruments" CASCADE;
TRUNCATE TABLE "public"."canonical_correction" CASCADE;
TRUNCATE TABLE "public"."corporate_action" CASCADE;
TRUNCATE TABLE "public"."dq_issue" CASCADE;
TRUNCATE TABLE "public"."futures_contract" CASCADE;
TRUNCATE TABLE "public"."instrument_identifiers" CASCADE;
TRUNCATE TABLE "public"."macro_series" CASCADE;
TRUNCATE TABLE "public"."macro_observation" CASCADE;
TRUNCATE TABLE "public"."market_data_eod" CASCADE;
TRUNCATE TABLE "public"."roll_rule" CASCADE;
TRUNCATE TABLE "public"."futures_continuous_eod" CASCADE;
TRUNCATE TABLE "public"."trading_calendar" CASCADE;

\copy "public"."dataset_registry" ("dataset_key", "name", "description", "asset_class", "market", "frequency", "is_active", "config", "created_at", "updated_at") FROM 'tables/public.dataset_registry.csv' WITH (FORMAT csv, HEADER true)
\copy "public"."ingestion_run" ("run_id", "dataset_key", "source", "request_key", "raw_records", "status", "started_at", "completed_at", "total_records", "success_records", "failed_records", "error_message", "metadata", "created_at") FROM 'tables/public.ingestion_run.csv' WITH (FORMAT csv, HEADER true)
\copy "public"."instruments" ("instrument_id", "asset_class", "market", "symbol", "name", "currency", "timezone", "status", "listed_date", "delisted_date", "extra", "created_at", "updated_at") FROM 'tables/public.instruments.csv' WITH (FORMAT csv, HEADER true)
\copy "public"."canonical_correction" ("id", "table_name", "record_id", "instrument_id", "trade_date", "corrected_by", "correction_reason", "before_snapshot", "after_snapshot", "created_at") FROM 'tables/public.canonical_correction.csv' WITH (FORMAT csv, HEADER true)
\copy "public"."corporate_action" ("action_id", "instrument_id", "action_type", "ex_date", "record_date", "pay_date", "ratio", "cash_amount", "currency", "extra", "source", "asof_ts", "run_id", "created_at", "updated_at") FROM 'tables/public.corporate_action.csv' WITH (FORMAT csv, HEADER true)
\copy "public"."dq_issue" ("id", "run_id", "instrument_id", "trade_date", "issue_type", "severity", "description", "raw_data", "resolved", "resolved_at", "created_at") FROM 'tables/public.dq_issue.csv' WITH (FORMAT csv, HEADER true)
\copy "public"."futures_contract" ("contract_id", "instrument_id", "contract_code", "contract_month", "expiry_date", "currency", "extra", "source", "asof_ts", "run_id", "created_at", "updated_at") FROM 'tables/public.futures_contract.csv' WITH (FORMAT csv, HEADER true)
\copy "public"."instrument_identifiers" ("id", "instrument_id", "id_type", "id_value", "source", "valid_from", "valid_to", "created_at") FROM 'tables/public.instrument_identifiers.csv' WITH (FORMAT csv, HEADER true)
\copy "public"."macro_series" ("series_id", "name", "unit", "frequency", "market", "source_code", "source", "created_at", "updated_at") FROM 'tables/public.macro_series.csv' WITH (FORMAT csv, HEADER true)
\copy "public"."macro_observation" ("id", "series_id", "obs_date", "value", "source", "asof_ts", "run_id", "created_at", "updated_at") FROM 'tables/public.macro_observation.csv' WITH (FORMAT csv, HEADER true)
\copy "public"."market_data_eod" ("id", "instrument_id", "trade_date", "open", "high", "low", "close", "volume", "turnover", "source", "asof_ts", "run_id", "created_at", "updated_at") FROM 'tables/public.market_data_eod.csv' WITH (FORMAT csv, HEADER true)
\copy "public"."roll_rule" ("rule_id", "name", "description", "config", "created_at", "updated_at") FROM 'tables/public.roll_rule.csv' WITH (FORMAT csv, HEADER true)
\copy "public"."futures_continuous_eod" ("id", "instrument_id", "roll_rule_id", "trade_date", "open", "high", "low", "close", "volume", "turnover", "source", "asof_ts", "run_id", "created_at", "updated_at") FROM 'tables/public.futures_continuous_eod.csv' WITH (FORMAT csv, HEADER true)
\copy "public"."trading_calendar" ("id", "market", "trade_date", "is_open", "session_open", "session_close", "holiday_name") FROM 'tables/public.trading_calendar.csv' WITH (FORMAT csv, HEADER true)

SET session_replication_role = origin;

COMMIT;
