-- Best-effort schema snapshot generated by scripts/partial_dump.py
-- For exact DDL, use pg_dump --schema-only

CREATE TABLE IF NOT EXISTS "public"."canonical_correction" (
    "id" uuid NOT NULL,
    "table_name" character varying(100) NOT NULL,
    "record_id" uuid NOT NULL,
    "instrument_id" uuid,
    "trade_date" date,
    "corrected_by" character varying(200) NOT NULL,
    "correction_reason" text NOT NULL,
    "before_snapshot" jsonb,
    "after_snapshot" jsonb,
    "created_at" timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."corporate_action" (
    "action_id" uuid NOT NULL,
    "instrument_id" uuid NOT NULL,
    "action_type" character varying(50) NOT NULL,
    "ex_date" date,
    "record_date" date,
    "pay_date" date,
    "ratio" numeric(20,8),
    "cash_amount" numeric(20,8),
    "currency" character varying(10),
    "extra" jsonb,
    "source" character varying(50),
    "asof_ts" timestamp with time zone NOT NULL,
    "run_id" uuid,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."dataset_registry" (
    "dataset_key" character varying(50) NOT NULL,
    "name" character varying(100) NOT NULL,
    "description" text,
    "asset_class" character varying(20) NOT NULL,
    "market" character varying(10) NOT NULL,
    "frequency" character varying(20) NOT NULL,
    "is_active" boolean NOT NULL,
    "config" jsonb,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."dq_issue" (
    "id" uuid NOT NULL,
    "run_id" uuid,
    "instrument_id" uuid,
    "trade_date" timestamp with time zone,
    "issue_type" character varying(50) NOT NULL,
    "severity" character varying(20) NOT NULL,
    "description" text,
    "raw_data" jsonb,
    "resolved" boolean NOT NULL,
    "resolved_at" timestamp with time zone,
    "created_at" timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."futures_continuous_eod" (
    "id" uuid NOT NULL,
    "instrument_id" uuid NOT NULL,
    "roll_rule_id" uuid,
    "trade_date" date NOT NULL,
    "open" numeric(20,8),
    "high" numeric(20,8),
    "low" numeric(20,8),
    "close" numeric(20,8),
    "volume" bigint,
    "turnover" numeric(20,4),
    "source" character varying(50),
    "asof_ts" timestamp with time zone NOT NULL,
    "run_id" uuid,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."futures_contract" (
    "contract_id" uuid NOT NULL,
    "instrument_id" uuid NOT NULL,
    "contract_code" character varying(50) NOT NULL,
    "contract_month" character varying(10),
    "expiry_date" date,
    "currency" character varying(10),
    "extra" jsonb,
    "source" character varying(50),
    "asof_ts" timestamp with time zone NOT NULL,
    "run_id" uuid,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."ingestion_run" (
    "run_id" uuid NOT NULL,
    "dataset_key" character varying(50) NOT NULL,
    "source" character varying(50),
    "request_key" character varying(100),
    "raw_records" integer NOT NULL,
    "status" character varying(30) NOT NULL,
    "started_at" timestamp with time zone,
    "completed_at" timestamp with time zone,
    "total_records" integer NOT NULL,
    "success_records" integer NOT NULL,
    "failed_records" integer NOT NULL,
    "error_message" text,
    "metadata" jsonb,
    "created_at" timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."instrument_identifiers" (
    "id" uuid NOT NULL,
    "instrument_id" uuid NOT NULL,
    "id_type" character varying(30) NOT NULL,
    "id_value" character varying(100) NOT NULL,
    "source" character varying(50),
    "valid_from" date,
    "valid_to" date,
    "created_at" timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."instruments" (
    "instrument_id" uuid NOT NULL,
    "asset_class" character varying(20) NOT NULL,
    "market" character varying(10) NOT NULL,
    "symbol" character varying(50) NOT NULL,
    "name" character varying(200),
    "currency" character varying(10),
    "timezone" character varying(50),
    "status" character varying(20) NOT NULL,
    "listed_date" date,
    "delisted_date" date,
    "extra" jsonb,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."macro_observation" (
    "id" uuid NOT NULL,
    "series_id" uuid NOT NULL,
    "obs_date" date NOT NULL,
    "value" numeric(20,8),
    "source" character varying(50),
    "asof_ts" timestamp with time zone NOT NULL,
    "run_id" uuid,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."macro_series" (
    "series_id" uuid NOT NULL,
    "name" character varying(200) NOT NULL,
    "unit" character varying(50),
    "frequency" character varying(20),
    "market" character varying(10),
    "source_code" character varying(100),
    "source" character varying(50),
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."market_data_eod" (
    "id" uuid NOT NULL,
    "instrument_id" uuid NOT NULL,
    "trade_date" date NOT NULL,
    "open" numeric(20,8),
    "high" numeric(20,8),
    "low" numeric(20,8),
    "close" numeric(20,8),
    "volume" bigint,
    "turnover" numeric(20,4),
    "source" character varying(50),
    "asof_ts" timestamp with time zone NOT NULL,
    "run_id" uuid,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."roll_rule" (
    "rule_id" uuid NOT NULL,
    "name" character varying(100) NOT NULL,
    "description" text,
    "config" jsonb,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."trading_calendar" (
    "id" uuid NOT NULL,
    "market" character varying(10) NOT NULL,
    "trade_date" date NOT NULL,
    "is_open" boolean NOT NULL,
    "session_open" time without time zone,
    "session_close" time without time zone,
    "holiday_name" character varying(100)
);

CREATE TABLE IF NOT EXISTS "raw"."market_payload" (
    "dataset_key" character varying(50) NOT NULL,
    "source" character varying(50) NOT NULL,
    "request_key" character varying(100) NOT NULL,
    "idempotency_key" character varying(100) NOT NULL,
    "payload" jsonb NOT NULL,
    "fetched_at" timestamp with time zone NOT NULL,
    "expire_at" timestamp with time zone NOT NULL,
    "run_id" uuid NOT NULL,
    "created_at" timestamp with time zone NOT NULL
);
