"""fix_ca_unique_constraint

Revision ID: 13bb20eec054
Revises: 9e246ab981f7
Create Date: 2026-04-24 16:56:00.680201
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "13bb20eec054"
down_revision: Union[str, Sequence[str], None] = "9e246ab981f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("idx_ca_inst_date"), table_name="corporate_action")
    op.create_unique_constraint(
        "uq_ca_instrument_action_date",
        "corporate_action",
        ["instrument_id", "action_type", "ex_date"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_ca_instrument_action_date", "corporate_action", type_="unique")
    op.create_index(
        op.f("idx_ca_inst_date"), "corporate_action", ["instrument_id", "ex_date"], unique=False
    )
    # ### end Alembic commands ###
