"""fix_ca_unique_constraint

Revision ID: 13bb20eec054
Revises: 9e246ab981f7
Create Date: 2026-04-24 16:56:00.680201
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "13bb20eec054"
down_revision: Union[str, Sequence[str], None] = "9e246ab981f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _raise_if_duplicate_business_keys_exist() -> None:
    """Fail clearly before PostgreSQL rejects the new unique constraint."""
    duplicate_stmt = sa.text("""
        SELECT
            instrument_id,
            action_type,
            ex_date,
            COUNT(*) AS duplicate_count
        FROM corporate_action
        WHERE ex_date IS NOT NULL
        GROUP BY instrument_id, action_type, ex_date
        HAVING COUNT(*) > 1
        ORDER BY duplicate_count DESC, instrument_id, action_type, ex_date
        LIMIT 10
        """)
    duplicates = list(op.get_bind().execute(duplicate_stmt).mappings())
    if not duplicates:
        return

    samples = "; ".join(
        (
            f"instrument_id={row['instrument_id']}, "
            f"action_type={row['action_type']}, "
            f"ex_date={row['ex_date']}, "
            f"count={row['duplicate_count']}"
        )
        for row in duplicates
    )
    raise RuntimeError(
        "Cannot create uq_ca_instrument_action_date because existing "
        "corporate_action rows contain duplicate business keys "
        "(instrument_id, action_type, ex_date). Clean or merge duplicates "
        f"before running this migration. Sample duplicates: {samples}"
    )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _raise_if_duplicate_business_keys_exist()
    op.drop_index(op.f("idx_ca_inst_date"), table_name="corporate_action")
    op.create_unique_constraint(
        "uq_ca_instrument_action_date",
        "corporate_action",
        ["instrument_id", "action_type", "ex_date"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_ca_instrument_action_date", "corporate_action", type_="unique")
    op.create_index(
        op.f("idx_ca_inst_date"), "corporate_action", ["instrument_id", "ex_date"], unique=False
    )
    # ### end Alembic commands ###
