"""instrument_identifier_nulls_not_distinct

Revision ID: 841728d7045e
Revises: 13bb20eec054
Create Date: 2026-04-29 11:37:01.753450
"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "841728d7045e"
down_revision: Union[str, Sequence[str], None] = "13bb20eec054"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        WITH ranked_identifiers AS (
            SELECT
                id,
                ROW_NUMBER() OVER (
                    PARTITION BY id_type, id_value, valid_from
                    ORDER BY created_at ASC NULLS LAST, id ASC
                ) AS row_num
            FROM instrument_identifiers
        )
        DELETE FROM instrument_identifiers
        WHERE id IN (
            SELECT id
            FROM ranked_identifiers
            WHERE row_num > 1
        )
        """)
    op.drop_constraint(op.f("uq_identifier"), "instrument_identifiers", type_="unique")
    op.create_unique_constraint(
        "uq_identifier",
        "instrument_identifiers",
        ["id_type", "id_value", "valid_from"],
        postgresql_nulls_not_distinct=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_identifier", "instrument_identifiers", type_="unique")
    op.create_unique_constraint(
        op.f("uq_identifier"),
        "instrument_identifiers",
        ["id_type", "id_value", "valid_from"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
