"""bootstrap schema

Revision ID: 9e246ab981f7
Revises: eb434be9f22a
Create Date: 2026-04-22 11:19:23.455869
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e246ab981f7'
down_revision: Union[str, Sequence[str], None] = 'eb434be9f22a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if inspector.has_table("instruments", schema="public"):
        return

    op.execute("CREATE SCHEMA IF NOT EXISTS raw")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset_registry',
    sa.Column('dataset_key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('asset_class', sa.String(length=20), nullable=False),
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('dataset_key', name=op.f('pk_dataset_registry'))
    )
    op.create_table('instruments',
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('asset_class', sa.String(length=20), nullable=False),
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('listed_date', sa.Date(), nullable=True),
    sa.Column('delisted_date', sa.Date(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('instrument_id', name=op.f('pk_instruments')),
    sa.UniqueConstraint('asset_class', 'market', 'symbol', name='uq_instrument')
    )
    op.create_index('idx_inst_market', 'instruments', ['market'], unique=False)
    op.create_index('idx_inst_status', 'instruments', ['status'], unique=False)
    op.create_table('macro_series',
    sa.Column('series_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=True),
    sa.Column('market', sa.String(length=10), nullable=True),
    sa.Column('source_code', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('series_id', name=op.f('pk_macro_series')),
    sa.UniqueConstraint('source_code', name='uq_macro_series_source_code')
    )
    op.create_index('idx_macro_market', 'macro_series', ['market'], unique=False)
    op.create_index('idx_macro_source_code', 'macro_series', ['source_code'], unique=False)
    op.create_table('market_payload',
    sa.Column('dataset_key', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('request_key', sa.String(length=100), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expire_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('idempotency_key', name=op.f('pk_market_payload')),
    schema='raw'
    )
    op.create_index('idx_mp_dataset', 'market_payload', ['dataset_key'], unique=False, schema='raw')
    op.create_index('idx_mp_expire', 'market_payload', ['expire_at'], unique=False, schema='raw')
    op.create_index('idx_mp_run', 'market_payload', ['run_id'], unique=False, schema='raw')
    op.create_table('roll_rule',
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('rule_id', name=op.f('pk_roll_rule')),
    sa.UniqueConstraint('name', name='uq_roll_rule')
    )
    op.create_table('trading_calendar',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('session_open', sa.Time(), nullable=True),
    sa.Column('session_close', sa.Time(), nullable=True),
    sa.Column('holiday_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trading_calendar')),
    sa.UniqueConstraint('market', 'trade_date', name='uq_calendar')
    )
    op.create_index('idx_cal_market_date', 'trading_calendar', ['market', 'trade_date'], unique=False)
    op.create_table('canonical_correction',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=True),
    sa.Column('trade_date', sa.Date(), nullable=True),
    sa.Column('corrected_by', sa.String(length=200), nullable=False),
    sa.Column('correction_reason', sa.Text(), nullable=False),
    sa.Column('before_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.instrument_id'], name=op.f('fk_canonical_correction_instrument_id_instruments'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_canonical_correction'))
    )
    op.create_index('idx_correction_created', 'canonical_correction', ['created_at'], unique=False)
    op.create_index('idx_correction_instrument', 'canonical_correction', ['instrument_id'], unique=False)
    op.create_index('idx_correction_record', 'canonical_correction', ['table_name', 'record_id'], unique=False)
    op.create_table('corporate_action',
    sa.Column('action_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('ex_date', sa.Date(), nullable=True),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.Column('pay_date', sa.Date(), nullable=True),
    sa.Column('ratio', sa.NUMERIC(precision=20, scale=8), nullable=True),
    sa.Column('cash_amount', sa.NUMERIC(precision=20, scale=8), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('asof_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.instrument_id'], name=op.f('fk_corporate_action_instrument_id_instruments')),
    sa.PrimaryKeyConstraint('action_id', name=op.f('pk_corporate_action'))
    )
    op.create_index('idx_ca_action', 'corporate_action', ['action_type'], unique=False)
    op.create_index('idx_ca_inst_date', 'corporate_action', ['instrument_id', 'ex_date'], unique=False)
    op.create_table('futures_continuous_eod',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('roll_rule_id', sa.UUID(), nullable=True),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.NUMERIC(precision=20, scale=8), nullable=True),
    sa.Column('high', sa.NUMERIC(precision=20, scale=8), nullable=True),
    sa.Column('low', sa.NUMERIC(precision=20, scale=8), nullable=True),
    sa.Column('close', sa.NUMERIC(precision=20, scale=8), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('turnover', sa.NUMERIC(precision=20, scale=4), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('asof_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.instrument_id'], name=op.f('fk_futures_continuous_eod_instrument_id_instruments')),
    sa.ForeignKeyConstraint(['roll_rule_id'], ['roll_rule.rule_id'], name=op.f('fk_futures_continuous_eod_roll_rule_id_roll_rule')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_futures_continuous_eod')),
    sa.UniqueConstraint('instrument_id', 'trade_date', name='uq_futures_cont_eod')
    )
    op.create_index('idx_fut_cont_date', 'futures_continuous_eod', ['trade_date'], unique=False)
    op.create_table('futures_contract',
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('contract_code', sa.String(length=50), nullable=False),
    sa.Column('contract_month', sa.String(length=10), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('asof_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.instrument_id'], name=op.f('fk_futures_contract_instrument_id_instruments')),
    sa.PrimaryKeyConstraint('contract_id', name=op.f('pk_futures_contract')),
    sa.UniqueConstraint('instrument_id', 'contract_code', name='uq_futures_contract')
    )
    op.create_index('idx_futures_expiry', 'futures_contract', ['expiry_date'], unique=False)
    op.create_table('ingestion_run',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('dataset_key', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('request_key', sa.String(length=100), nullable=True),
    sa.Column('raw_records', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.Column('success_records', sa.Integer(), nullable=False),
    sa.Column('failed_records', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_key'], ['dataset_registry.dataset_key'], name=op.f('fk_ingestion_run_dataset_key_dataset_registry')),
    sa.PrimaryKeyConstraint('run_id', name=op.f('pk_ingestion_run'))
    )
    op.create_index('idx_run_dataset', 'ingestion_run', ['dataset_key'], unique=False)
    op.create_index('idx_run_status', 'ingestion_run', ['status'], unique=False)
    op.create_table('instrument_identifiers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('id_type', sa.String(length=30), nullable=False),
    sa.Column('id_value', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.instrument_id'], name=op.f('fk_instrument_identifiers_instrument_id_instruments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instrument_identifiers')),
    sa.UniqueConstraint('id_type', 'id_value', 'valid_from', name='uq_identifier')
    )
    op.create_index('idx_ident_inst', 'instrument_identifiers', ['instrument_id'], unique=False)
    op.create_index('idx_ident_type_value', 'instrument_identifiers', ['id_type', 'id_value'], unique=False)
    op.create_table('macro_observation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('series_id', sa.UUID(), nullable=False),
    sa.Column('obs_date', sa.Date(), nullable=False),
    sa.Column('value', sa.NUMERIC(precision=20, scale=8), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('asof_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['macro_series.series_id'], name=op.f('fk_macro_observation_series_id_macro_series')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_macro_observation')),
    sa.UniqueConstraint('series_id', 'obs_date', name='uq_macro_observation')
    )
    op.create_index('idx_macro_obs_date', 'macro_observation', ['obs_date'], unique=False)
    op.create_index('idx_macro_obs_series', 'macro_observation', ['series_id'], unique=False)
    op.create_table('market_data_eod',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.NUMERIC(precision=20, scale=8), nullable=True),
    sa.Column('high', sa.NUMERIC(precision=20, scale=8), nullable=True),
    sa.Column('low', sa.NUMERIC(precision=20, scale=8), nullable=True),
    sa.Column('close', sa.NUMERIC(precision=20, scale=8), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('turnover', sa.NUMERIC(precision=20, scale=4), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('asof_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.instrument_id'], name=op.f('fk_market_data_eod_instrument_id_instruments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_data_eod')),
    sa.UniqueConstraint('instrument_id', 'trade_date', name='uq_eod')
    )
    op.create_index('idx_eod_date', 'market_data_eod', ['trade_date'], unique=False)
    op.create_index('idx_eod_inst_date', 'market_data_eod', ['instrument_id', 'trade_date'], unique=False)
    op.create_table('dq_issue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('instrument_id', sa.UUID(), nullable=True),
    sa.Column('trade_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('issue_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.instrument_id'], name=op.f('fk_dq_issue_instrument_id_instruments')),
    sa.ForeignKeyConstraint(['run_id'], ['ingestion_run.run_id'], name=op.f('fk_dq_issue_run_id_ingestion_run')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dq_issue'))
    )
    op.create_index('idx_dq_resolved', 'dq_issue', ['resolved'], unique=False)
    op.create_index('idx_dq_run', 'dq_issue', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if not inspector.has_table("instruments", schema="public"):
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_dq_run', table_name='dq_issue')
    op.drop_index('idx_dq_resolved', table_name='dq_issue')
    op.drop_table('dq_issue')
    op.drop_index('idx_eod_inst_date', table_name='market_data_eod')
    op.drop_index('idx_eod_date', table_name='market_data_eod')
    op.drop_table('market_data_eod')
    op.drop_index('idx_macro_obs_series', table_name='macro_observation')
    op.drop_index('idx_macro_obs_date', table_name='macro_observation')
    op.drop_table('macro_observation')
    op.drop_index('idx_ident_type_value', table_name='instrument_identifiers')
    op.drop_index('idx_ident_inst', table_name='instrument_identifiers')
    op.drop_table('instrument_identifiers')
    op.drop_index('idx_run_status', table_name='ingestion_run')
    op.drop_index('idx_run_dataset', table_name='ingestion_run')
    op.drop_table('ingestion_run')
    op.drop_index('idx_futures_expiry', table_name='futures_contract')
    op.drop_table('futures_contract')
    op.drop_index('idx_fut_cont_date', table_name='futures_continuous_eod')
    op.drop_table('futures_continuous_eod')
    op.drop_index('idx_ca_inst_date', table_name='corporate_action')
    op.drop_index('idx_ca_action', table_name='corporate_action')
    op.drop_table('corporate_action')
    op.drop_index('idx_correction_record', table_name='canonical_correction')
    op.drop_index('idx_correction_instrument', table_name='canonical_correction')
    op.drop_index('idx_correction_created', table_name='canonical_correction')
    op.drop_table('canonical_correction')
    op.drop_index('idx_cal_market_date', table_name='trading_calendar')
    op.drop_table('trading_calendar')
    op.drop_table('roll_rule')
    op.drop_index('idx_mp_run', table_name='market_payload', schema='raw')
    op.drop_index('idx_mp_expire', table_name='market_payload', schema='raw')
    op.drop_index('idx_mp_dataset', table_name='market_payload', schema='raw')
    op.drop_table('market_payload', schema='raw')
    op.drop_index('idx_macro_source_code', table_name='macro_series')
    op.drop_index('idx_macro_market', table_name='macro_series')
    op.drop_table('macro_series')
    op.drop_index('idx_inst_status', table_name='instruments')
    op.drop_index('idx_inst_market', table_name='instruments')
    op.drop_table('instruments')
    op.drop_table('dataset_registry')
    # ### end Alembic commands ###
