"""add_message_id_to_ingestion_run

Revision ID: ad3d1c2c32cf
Revises: d8b9c6b4d732
Create Date: 2026-05-08 14:15:07.676538
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ad3d1c2c32cf"
down_revision: Union[str, Sequence[str], None] = "d8b9c6b4d732"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ingestion_run", sa.Column("message_id", sa.String(length=100), nullable=True))
    op.create_index(
        op.f("ix_ingestion_run_message_id"), "ingestion_run", ["message_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ingestion_run_message_id"), table_name="ingestion_run")
    op.drop_column("ingestion_run", "message_id")
    # ### end Alembic commands ###
