"""add_message_id_to_raw_market_payload

Revision ID: b54de58fafa1
Revises: ad3d1c2c32cf
Create Date: 2026-05-08 14:36:13.250286
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b54de58fafa1"
down_revision: Union[str, Sequence[str], None] = "ad3d1c2c32cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "market_payload",
        sa.Column("message_id", sa.String(length=100), nullable=True),
        schema="raw",
    )
    op.create_index(
        op.f("ix_raw_market_payload_message_id"),
        "market_payload",
        ["message_id"],
        unique=False,
        schema="raw",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_raw_market_payload_message_id"), table_name="market_payload", schema="raw"
    )
    op.drop_column("market_payload", "message_id", schema="raw")
    # ### end Alembic commands ###
